# Basic Python

## 1. Split this string

In [1]:
s = "Hi there Sam!"

In [2]:
res = s.split()
res

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [3]:
planet = "Earth"
diameter = 12742

In [4]:
print("The diameter of {0} is {1} kilometers.".format(planet, diameter))

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [5]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [6]:
lst = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]
a=lst[3][1][2];
print(a)

['hello']


# Numpy

In [7]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [8]:
array=np.zeros(10)

In [9]:
array=np.ones(10)*5

## 5. Create an array of all the even integers from 20 to 35

In [12]:
array=np.arange(20,35,2)

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [16]:
x =  np.arange(2, 11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [25]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.concatenate((a,b), axis=0)

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [18]:
import pandas as pd

In [22]:
data = [[1, 'Praabindh'], [2, 'Princy'], [3, 'Pranav']]
df = pd.DataFrame(data, columns=['SN', "Name"])
df

SN       Name
0   1  Praabindh
1   2     Princy
2   3     Pranav

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [26]:
import datetime

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [20]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [21]:
df = pd.DataFrame(lists, columns =['SI', 'Tag', 'Number']) 
print(df)

   SI  Tag  Number
0   1  aaa      22
1   2  bbb      25
2   3  ccc      24
